Bungie:
  clan_group_id: 0
  oauth_client_id: 0
  api_key: ''

Discord:
  api_key: ''

Resources:
  image_bucket_root_url: ''

Voluspa:
  prefix: '$'
  redis_path: ''
  memcache_path: ''
  vanguard_channel_id: 513522333231742987
