name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
